# Generated by Django 2.0 on 2018-07-27 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180727_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='publish_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
