# Generated by Django 2.0 on 2018-07-28 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180727_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_done_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='scheduled_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
